version: "3.9"
services:
  db:
    image: postgres:latest
    container_name: postgres_db
    env_file:
      - .env
    ports:
      - "5436:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

  app:
    build: .
    container_name: fastapi_app
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "${API_PORT}:8000"
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]

volumes:
  db_data:
