version: "3.9"
services:
  db:
    image: postgres:latest
    container_name: postgres_db
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: fastapi_app
    ports:
      - "${API_PORT}:${API_PORT}"
    depends_on:
      - db
    env_file:
      - .env

volumes:
  postgres_data:
